# This file is autogenerated to run all tests in the context of your Genie app.
# It is not necessary to edit this file.
# To create tests, simply add `.jl` test files in the `test/` folder.
# All `.jl` files in the `test/` folder will be automaticlaly executed by running `$ julia --project runtests.jl`
# If you want to selectively run tests, use `$ julia --project runtests.jl test_file_1 test_file_2`

ENV["GENIE_ENV"] = "test"
push!(LOAD_PATH, abspath(normpath(joinpath("..", "src"))))

cd("..")
using Pkg
Pkg.activate(".")

using Genie
using SearchLight


Genie.loadapp()
# has to run twice because of big with loading order of resources.
Genie.loadapp()

cd(@__DIR__)
Pkg.activate(".")

using Main.UserApp, Test, TestSetExtensions, Logging


Logging.global_logger(NullLogger())

@testset ExtendedTestSet "CbrnAlert app tests" begin
    include("db_setup_test.jl")
    @includetests ARGS
end