# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    LoginPostRequest(;
        email=nothing,
        password=nothing,
    )

    - email::String
    - password::String
"""
Base.@kwdef mutable struct LoginPostRequest <: OpenAPI.APIModel
    email::Union{Nothing, String} = nothing
    password::Union{Nothing, String} = nothing

    function LoginPostRequest(email, password, )
        OpenAPI.validate_property(LoginPostRequest, Symbol("email"), email)
        OpenAPI.validate_property(LoginPostRequest, Symbol("password"), password)
        return new(email, password, )
    end
end # type LoginPostRequest

const _property_types_LoginPostRequest = Dict{Symbol,String}(Symbol("email")=>"String", Symbol("password")=>"String", )
OpenAPI.property_type(::Type{ LoginPostRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LoginPostRequest[name]))}

function check_required(o::LoginPostRequest)
    o.email === nothing && (return false)
    o.password === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ LoginPostRequest }, name::Symbol, val)
end
