# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    GeoCellAllOfProperties(;
        val=nothing,
    )

    - val::Float64
"""
Base.@kwdef mutable struct GeoCellAllOfProperties <: OpenAPI.APIModel
    val::Union{Nothing, Float64} = nothing

    function GeoCellAllOfProperties(val, )
        OpenAPI.validate_property(GeoCellAllOfProperties, Symbol("val"), val)
        return new(val, )
    end
end # type GeoCellAllOfProperties

const _property_types_GeoCellAllOfProperties = Dict{Symbol,String}(Symbol("val")=>"Float64", )
OpenAPI.property_type(::Type{ GeoCellAllOfProperties }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoCellAllOfProperties[name]))}

function check_required(o::GeoCellAllOfProperties)
    o.val === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoCellAllOfProperties }, name::Symbol, val)
end
