# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeoJSon &#39;FeatureCollection&#39; object

    FeatureCollection(;
        type=nothing,
        bbox=nothing,
        features=nothing,
    )

    - type::String
    - bbox::Vector{Float64}
    - features::Vector{Feature}
"""
Base.@kwdef mutable struct FeatureCollection <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    bbox::Union{Nothing, Vector{Float64}} = nothing
    features::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Feature} }

    function FeatureCollection(type, bbox, features, )
        OpenAPI.validate_property(FeatureCollection, Symbol("type"), type)
        OpenAPI.validate_property(FeatureCollection, Symbol("bbox"), bbox)
        OpenAPI.validate_property(FeatureCollection, Symbol("features"), features)
        return new(type, bbox, features, )
    end
end # type FeatureCollection

const _property_types_FeatureCollection = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("bbox")=>"Vector{Float64}", Symbol("features")=>"Vector{Feature}", )
OpenAPI.property_type(::Type{ FeatureCollection }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FeatureCollection[name]))}

function check_required(o::FeatureCollection)
    o.type === nothing && (return false)
    o.features === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ FeatureCollection }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "FeatureCollection", :enum, val, ["Feature", "FeatureCollection", "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection"])
    end
end
