# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    Atp45WeatherManualStability(;
        stabilityClass=nothing,
    )

    - stabilityClass::Atp45StabilityClasses
"""
Base.@kwdef mutable struct Atp45WeatherManualStability <: OpenAPI.APIModel
    stabilityClass = nothing # spec type: Union{ Nothing, Atp45StabilityClasses }

    function Atp45WeatherManualStability(stabilityClass, )
        OpenAPI.validate_property(Atp45WeatherManualStability, Symbol("stabilityClass"), stabilityClass)
        return new(stabilityClass, )
    end
end # type Atp45WeatherManualStability

const _property_types_Atp45WeatherManualStability = Dict{Symbol,String}(Symbol("stabilityClass")=>"Atp45StabilityClasses", )
OpenAPI.property_type(::Type{ Atp45WeatherManualStability }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Atp45WeatherManualStability[name]))}

function check_required(o::Atp45WeatherManualStability)
    o.stabilityClass === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Atp45WeatherManualStability }, name::Symbol, val)
end
