# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    GeoPoint(;
        lon=nothing,
        lat=nothing,
    )

    - lon::Float64 : Longitude [°]
    - lat::Float64 : Latitude [°]
"""
Base.@kwdef mutable struct GeoPoint <: OpenAPI.APIModel
    lon::Union{Nothing, Float64} = nothing
    lat::Union{Nothing, Float64} = nothing

    function GeoPoint(lon, lat, )
        OpenAPI.validate_property(GeoPoint, Symbol("lon"), lon)
        OpenAPI.validate_property(GeoPoint, Symbol("lat"), lat)
        return new(lon, lat, )
    end
end # type GeoPoint

const _property_types_GeoPoint = Dict{Symbol,String}(Symbol("lon")=>"Float64", Symbol("lat")=>"Float64", )
OpenAPI.property_type(::Type{ GeoPoint }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoPoint[name]))}

function check_required(o::GeoPoint)
    o.lon === nothing && (return false)
    o.lat === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoPoint }, name::Symbol, val)
end
