# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    FlexpartInputError(;
        error=nothing,
        info=nothing,
        code=nothing,
    )

    - error::String
    - info::String
    - code::WeatherRetrievalErrorCode
"""
Base.@kwdef mutable struct FlexpartInputError <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing
    info::Union{Nothing, String} = nothing
    code = nothing # spec type: Union{ Nothing, WeatherRetrievalErrorCode }

    function FlexpartInputError(error, info, code, )
        OpenAPI.validate_property(FlexpartInputError, Symbol("error"), error)
        OpenAPI.validate_property(FlexpartInputError, Symbol("info"), info)
        OpenAPI.validate_property(FlexpartInputError, Symbol("code"), code)
        return new(error, info, code, )
    end
end # type FlexpartInputError

const _property_types_FlexpartInputError = Dict{Symbol,String}(Symbol("error")=>"String", Symbol("info")=>"String", Symbol("code")=>"WeatherRetrievalErrorCode", )
OpenAPI.property_type(::Type{ FlexpartInputError }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FlexpartInputError[name]))}

function check_required(o::FlexpartInputError)
    true
end

function OpenAPI.validate_property(::Type{ FlexpartInputError }, name::Symbol, val)
end
