# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""
    GeoJsonSliceResponseMetadata(; value=nothing)
"""
mutable struct GeoJsonSliceResponseMetadata <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ColorbarData }
    GeoJsonSliceResponseMetadata() = new()
    GeoJsonSliceResponseMetadata(value) = new(value)
end # type GeoJsonSliceResponseMetadata

function OpenAPI.property_type(::Type{ GeoJsonSliceResponseMetadata }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(GeoJsonSliceResponseMetadata, name)
end
