# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    Atp45DecisionTreeAllOf(;
        children=nothing,
    )

    - children::Vector{Atp45DecisionTree}
"""
Base.@kwdef mutable struct Atp45DecisionTreeAllOf <: OpenAPI.APIModel
    children::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Atp45DecisionTree} }

    function Atp45DecisionTreeAllOf(children, )
        OpenAPI.validate_property(Atp45DecisionTreeAllOf, Symbol("children"), children)
        return new(children, )
    end
end # type Atp45DecisionTreeAllOf

const _property_types_Atp45DecisionTreeAllOf = Dict{Symbol,String}(Symbol("children")=>"Vector{Atp45DecisionTree}", )
OpenAPI.property_type(::Type{ Atp45DecisionTreeAllOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Atp45DecisionTreeAllOf[name]))}

function check_required(o::Atp45DecisionTreeAllOf)
    o.children === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Atp45DecisionTreeAllOf }, name::Symbol, val)
end
