# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Application specific error code when a Flexpart run fails. Possible values area: - &#39;noMeteoFieldsAvailable&#39;: The Flexpart run time window exceeds the available meteorological fields valid time. - &#39;unknownFlexpartRunError&#39;: Flexpart run error that couldn&#39;t be identified.

    FlexpartRunErrorCode(;
    )

"""
Base.@kwdef mutable struct FlexpartRunErrorCode <: OpenAPI.APIModel

    function FlexpartRunErrorCode()
        return new()
    end
end # type FlexpartRunErrorCode

const _property_types_FlexpartRunErrorCode = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ FlexpartRunErrorCode }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FlexpartRunErrorCode[name]))}

function check_required(o::FlexpartRunErrorCode)
    true
end

function OpenAPI.validate_property(::Type{ FlexpartRunErrorCode }, name::Symbol, val)
end
