# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    GeoJsonSliceResponseCollectionAllOf(;
        features=nothing,
    )

    - features::Vector{GeoCell}
"""
Base.@kwdef mutable struct GeoJsonSliceResponseCollectionAllOf <: OpenAPI.APIModel
    features::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{GeoCell} }

    function GeoJsonSliceResponseCollectionAllOf(features, )
        OpenAPI.validate_property(GeoJsonSliceResponseCollectionAllOf, Symbol("features"), features)
        return new(features, )
    end
end # type GeoJsonSliceResponseCollectionAllOf

const _property_types_GeoJsonSliceResponseCollectionAllOf = Dict{Symbol,String}(Symbol("features")=>"Vector{GeoCell}", )
OpenAPI.property_type(::Type{ GeoJsonSliceResponseCollectionAllOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonSliceResponseCollectionAllOf[name]))}

function check_required(o::GeoJsonSliceResponseCollectionAllOf)
    o.features === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonSliceResponseCollectionAllOf }, name::Symbol, val)
end
