# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    Atp45RunTypes(;
    )

"""
Base.@kwdef mutable struct Atp45RunTypes <: OpenAPI.APIModel

    function Atp45RunTypes()
        return new()
    end
end # type Atp45RunTypes

const _property_types_Atp45RunTypes = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ Atp45RunTypes }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Atp45RunTypes[name]))}

function check_required(o::Atp45RunTypes)
    true
end

function OpenAPI.validate_property(::Type{ Atp45RunTypes }, name::Symbol, val)
end
