# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Application specific error code when a retrieval to MARS from ECMWF fails. Possible values area: - &#39;dataNotYetAvailable&#39;: The requested weather data are not available yet. - &#39;unknownMarsError&#39;: MARS error that couldn&#39;t be identified.

    WeatherRetrievalErrorCode(;
    )

"""
Base.@kwdef mutable struct WeatherRetrievalErrorCode <: OpenAPI.APIModel

    function WeatherRetrievalErrorCode()
        return new()
    end
end # type WeatherRetrievalErrorCode

const _property_types_WeatherRetrievalErrorCode = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ WeatherRetrievalErrorCode }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WeatherRetrievalErrorCode[name]))}

function check_required(o::WeatherRetrievalErrorCode)
    true
end

function OpenAPI.validate_property(::Type{ WeatherRetrievalErrorCode }, name::Symbol, val)
end
