# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    ForecastStep(;
        start=nothing,
        leadtime=nothing,
    )

    - start::ZonedDateTime
    - leadtime::ZonedDateTime
"""
Base.@kwdef mutable struct ForecastStep <: OpenAPI.APIModel
    start::Union{Nothing, ZonedDateTime} = nothing
    leadtime::Union{Nothing, ZonedDateTime} = nothing

    function ForecastStep(start, leadtime, )
        OpenAPI.validate_property(ForecastStep, Symbol("start"), start)
        OpenAPI.validate_property(ForecastStep, Symbol("leadtime"), leadtime)
        return new(start, leadtime, )
    end
end # type ForecastStep

const _property_types_ForecastStep = Dict{Symbol,String}(Symbol("start")=>"ZonedDateTime", Symbol("leadtime")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ ForecastStep }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ForecastStep[name]))}

function check_required(o::ForecastStep)
    o.start === nothing && (return false)
    o.leadtime === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ForecastStep }, name::Symbol, val)
    if name === Symbol("start")
        OpenAPI.validate_param(name, "ForecastStep", :format, val, "date-time")
    end
    if name === Symbol("leadtime")
        OpenAPI.validate_param(name, "ForecastStep", :format, val, "date-time")
    end
end
