# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Error when a Flexpart run fails.

    FlexpartRunError(;
        error=nothing,
        info=nothing,
        code=nothing,
    )

    - error::String
    - info::String
    - code::FlexpartRunErrorCode
"""
Base.@kwdef mutable struct FlexpartRunError <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing
    info::Union{Nothing, String} = nothing
    code = nothing # spec type: Union{ Nothing, FlexpartRunErrorCode }

    function FlexpartRunError(error, info, code, )
        OpenAPI.validate_property(FlexpartRunError, Symbol("error"), error)
        OpenAPI.validate_property(FlexpartRunError, Symbol("info"), info)
        OpenAPI.validate_property(FlexpartRunError, Symbol("code"), code)
        return new(error, info, code, )
    end
end # type FlexpartRunError

const _property_types_FlexpartRunError = Dict{Symbol,String}(Symbol("error")=>"String", Symbol("info")=>"String", Symbol("code")=>"FlexpartRunErrorCode", )
OpenAPI.property_type(::Type{ FlexpartRunError }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FlexpartRunError[name]))}

function check_required(o::FlexpartRunError)
    true
end

function OpenAPI.validate_property(::Type{ FlexpartRunError }, name::Symbol, val)
end
