# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    Atp45StabilityClasses(;
    )

"""
Base.@kwdef mutable struct Atp45StabilityClasses <: OpenAPI.APIModel

    function Atp45StabilityClasses()
        return new()
    end
end # type Atp45StabilityClasses

const _property_types_Atp45StabilityClasses = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ Atp45StabilityClasses }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Atp45StabilityClasses[name]))}

function check_required(o::Atp45StabilityClasses)
    true
end

function OpenAPI.validate_property(::Type{ Atp45StabilityClasses }, name::Symbol, val)
end
