# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    WindVelocity(;
        speed=nothing,
        azimuth=nothing,
    )

    - speed::Float64 : Wind speed - units [m/s]
    - azimuth::Float64 : angle from North - units [m/s]
"""
Base.@kwdef mutable struct WindVelocity <: OpenAPI.APIModel
    speed::Union{Nothing, Float64} = nothing
    azimuth::Union{Nothing, Float64} = nothing

    function WindVelocity(speed, azimuth, )
        OpenAPI.validate_property(WindVelocity, Symbol("speed"), speed)
        OpenAPI.validate_property(WindVelocity, Symbol("azimuth"), azimuth)
        return new(speed, azimuth, )
    end
end # type WindVelocity

const _property_types_WindVelocity = Dict{Symbol,String}(Symbol("speed")=>"Float64", Symbol("azimuth")=>"Float64", )
OpenAPI.property_type(::Type{ WindVelocity }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WindVelocity[name]))}

function check_required(o::WindVelocity)
    o.speed === nothing && (return false)
    o.azimuth === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WindVelocity }, name::Symbol, val)
end
