# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Weather conditions description for ATP45, in case it is provided by the user.

    Atp45WeatherManual(;
        wind=nothing,
        stability=nothing,
    )

    - wind::WindVelocity
    - stability::Atp45WeatherManualStability
"""
Base.@kwdef mutable struct Atp45WeatherManual <: OpenAPI.APIModel
    wind = nothing # spec type: Union{ Nothing, WindVelocity }
    stability = nothing # spec type: Union{ Nothing, Atp45WeatherManualStability }

    function Atp45WeatherManual(wind, stability, )
        OpenAPI.validate_property(Atp45WeatherManual, Symbol("wind"), wind)
        OpenAPI.validate_property(Atp45WeatherManual, Symbol("stability"), stability)
        return new(wind, stability, )
    end
end # type Atp45WeatherManual

const _property_types_Atp45WeatherManual = Dict{Symbol,String}(Symbol("wind")=>"WindVelocity", Symbol("stability")=>"Atp45WeatherManualStability", )
OpenAPI.property_type(::Type{ Atp45WeatherManual }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Atp45WeatherManual[name]))}

function check_required(o::Atp45WeatherManual)
    o.wind === nothing && (return false)
    o.stability === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Atp45WeatherManual }, name::Symbol, val)
end
