# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    GeometryElementAllOf(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct GeometryElementAllOf <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function GeometryElementAllOf(type, )
        OpenAPI.validate_property(GeometryElementAllOf, Symbol("type"), type)
        return new(type, )
    end
end # type GeometryElementAllOf

const _property_types_GeometryElementAllOf = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ GeometryElementAllOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeometryElementAllOf[name]))}

function check_required(o::GeometryElementAllOf)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeometryElementAllOf }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "GeometryElementAllOf", :enum, val, ["Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon"])
    end
end
