# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""
    Atp45InputWeatherInput(; value=nothing)
"""
mutable struct Atp45InputWeatherInput <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Atp45InputWeatherInputOneOf, Atp45WeatherManual, ForecastStep }
    Atp45InputWeatherInput() = new()
    Atp45InputWeatherInput(value) = new(value)
end # type Atp45InputWeatherInput

function OpenAPI.property_type(::Type{ Atp45InputWeatherInput }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(Atp45InputWeatherInput, name)
end
