# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    GeoJsonSliceResponseCollection(;
        type=nothing,
        bbox=nothing,
        features=nothing,
    )

    - type::String
    - bbox::Vector{Float64}
    - features::Vector{GeoCell}
"""
Base.@kwdef mutable struct GeoJsonSliceResponseCollection <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    bbox::Union{Nothing, Vector{Float64}} = nothing
    features::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{GeoCell} }

    function GeoJsonSliceResponseCollection(type, bbox, features, )
        OpenAPI.validate_property(GeoJsonSliceResponseCollection, Symbol("type"), type)
        OpenAPI.validate_property(GeoJsonSliceResponseCollection, Symbol("bbox"), bbox)
        OpenAPI.validate_property(GeoJsonSliceResponseCollection, Symbol("features"), features)
        return new(type, bbox, features, )
    end
end # type GeoJsonSliceResponseCollection

const _property_types_GeoJsonSliceResponseCollection = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("bbox")=>"Vector{Float64}", Symbol("features")=>"Vector{GeoCell}", )
OpenAPI.property_type(::Type{ GeoJsonSliceResponseCollection }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonSliceResponseCollection[name]))}

function check_required(o::GeoJsonSliceResponseCollection)
    o.type === nothing && (return false)
    o.features === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonSliceResponseCollection }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "GeoJsonSliceResponseCollection", :enum, val, ["Feature", "FeatureCollection", "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection"])
    end
end
