# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Abstract type for all GeoJSon object except Feature and FeatureCollection 

    Geometry(;
        type=nothing,
        bbox=nothing,
    )

    - type::String
    - bbox::Vector{Float64}
"""
Base.@kwdef mutable struct Geometry <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    bbox::Union{Nothing, Vector{Float64}} = nothing

    function Geometry(type, bbox, )
        OpenAPI.validate_property(Geometry, Symbol("type"), type)
        OpenAPI.validate_property(Geometry, Symbol("bbox"), bbox)
        return new(type, bbox, )
    end
end # type Geometry

const _property_types_Geometry = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("bbox")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ Geometry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Geometry[name]))}

function check_required(o::Geometry)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Geometry }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "Geometry", :enum, val, ["Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection"])
    end
end
