# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    RunStatus(;
    )

"""
Base.@kwdef mutable struct RunStatus <: OpenAPI.APIModel

    function RunStatus()
        return new()
    end
end # type RunStatus

const _property_types_RunStatus = Dict{Symbol,String}()
OpenAPI.property_type(::Type{ RunStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RunStatus[name]))}

function check_required(o::RunStatus)
    true
end

function OpenAPI.validate_property(::Type{ RunStatus }, name::Symbol, val)
end
