name: cbrnalert
services:
  backend:
    build: 
      context: ../ # Root of the project
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ${ECMWF_API_RC_FILE}:/root/.ecmwfapirc
    container_name: cbrnalert-backend
    expose:
      - "${BACKEND_PORT}"       # Expose port 8000 for internal access
    environment:
      - JULIA_DEPOT_PATH=/root/.julia
      # - CORS_ALLOWED_ORIGINS=http://localhost:80
    networks:
      - cbrnalert-network
    restart: unless-stopped

  frontend:
    build: 
      context: ../
      dockerfile: docker/frontend/Dockerfile
      target: production-stage  # Build only the production stage
    container_name: cbrnalert-frontend
    ports:
      - "${APP_PORT}:${FRONTEND_PORT}"
    networks:
      - cbrnalert-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  julia-depot:

networks:
  cbrnalert-network:
    driver: bridge
