/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Atp45ResultCollection } from './atp45ResultCollection';
import { Atp45ResultMetadata } from './atp45ResultMetadata';


export interface Atp45Result { 
    collection: Atp45ResultCollection;
    metadata?: Atp45ResultMetadata;
}

