/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Atp45ZoneAllOfProperties } from './atp45ZoneAllOfProperties';
import { Polygon } from './polygon';
import { Feature } from './feature';


export interface Atp45Zone extends Feature {
    properties: Atp45ZoneAllOfProperties;
    geometry: Polygon;
}
export namespace Atp45Zone {
}


