/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoRectangle } from './geoRectangle';


/**
 * Simplified data structure needed for a retrieval of meteorological data for Flexpart
 */
export interface FlexpartRetrieveSimple { 
    area: GeoRectangle;
    start: string;
    end: string;
    /**
     * units: [°]
     */
    gridres: number;
    /**
     * units: [s]
     */
    timeStep: number;
}

