/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeometryAllOf { 
    type: GeometryAllOf.TypeEnum;
}
export namespace GeometryAllOf {
    export type TypeEnum = 'Point' | 'MultiPoint' | 'LineString' | 'MultiLineString' | 'Polygon' | 'MultiPolygon' | 'GeometryCollection';
    export const TypeEnum = {
        Point: 'Point' as TypeEnum,
        MultiPoint: 'MultiPoint' as TypeEnum,
        LineString: 'LineString' as TypeEnum,
        MultiLineString: 'MultiLineString' as TypeEnum,
        Polygon: 'Polygon' as TypeEnum,
        MultiPolygon: 'MultiPolygon' as TypeEnum,
        GeometryCollection: 'GeometryCollection' as TypeEnum
    };
}


