/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WindVelocity } from './windVelocity';


export interface WindAtp45InputAllOf { 
    wind: WindVelocity;
    stabilityClass: WindAtp45InputAllOf.StabilityClassEnum;
}
export namespace WindAtp45InputAllOf {
    export type StabilityClassEnum = 'Unstable' | 'Neutral' | 'Stable';
    export const StabilityClassEnum = {
        Unstable: 'Unstable' as StabilityClassEnum,
        Neutral: 'Neutral' as StabilityClassEnum,
        Stable: 'Stable' as StabilityClassEnum
    };
}


