# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


function login_post_read(handler)
    function login_post_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        openapi_params["LoginPostRequest"] = OpenAPI.Servers.to_param_type(LoginPostRequest, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function login_post_validate(handler)
    function login_post_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function login_post_invoke(impl; post_invoke=nothing)
    function login_post_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.login_post(req::HTTP.Request, openapi_params["LoginPostRequest"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerAuthApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "POST", path_prefix * "/login", OpenAPI.Servers.middleware(impl, login_post_read, login_post_validate, login_post_invoke; optional_middlewares...))
    return router
end
