/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Geometry } from './geometry';

import { GeoJsonObject } from './geoJsonObject';


/**
 * GeoJSon \'Feature\' object
 */
export interface Feature extends GeoJsonObject {
    geometry: Geometry;
    properties: object | null;
    id?: number | string | null;
}
export namespace Feature {
}


