/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FlexpartCommandSimple { 
    start: string;
    end: string;
    /**
     * units: [s]
     */
    timeStep: number;
    specie?: string;
    /**
     * Units for the output (see Flexpart docs)
     */
    outputType: number;
}

