/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPoint } from './geoPoint';


export interface FlexpartReleaseSimple { 
    location: GeoPoint;
    start: string;
    end: string;
    height: number;
    mass: number;
    particles?: number;
}

