/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlexpartCommandSimple } from './flexpartCommandSimple';
import { FlexpartOutgridSimple } from './flexpartOutgridSimple';
import { FlexpartReleaseSimple } from './flexpartReleaseSimple';
import { FlexpartOptionsSimple } from './flexpartOptionsSimple';


/**
 * @type FlexpartRunPostRequest
 * @export
 */
export type FlexpartRunPostRequest = FlexpartOptionsSimple;

