/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GeoJSon object The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) datum, with longitude and latitude units of decimal degrees. This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid. In the absence of elevation values, applications sensitive to height or depth SHOULD interpret positions as being at local ground or sea level. 
 */
export interface GeoJsonObject { 
    type: GeoJsonObject.TypeEnum;
    bbox?: Array<number>;
}
export namespace GeoJsonObject {
    export type TypeEnum = 'Feature' | 'FeatureCollection' | 'Point' | 'MultiPoint' | 'LineString' | 'MultiLineString' | 'Polygon' | 'MultiPolygon' | 'GeometryCollection';
    export const TypeEnum = {
        Feature: 'Feature' as TypeEnum,
        FeatureCollection: 'FeatureCollection' as TypeEnum,
        Point: 'Point' as TypeEnum,
        MultiPoint: 'MultiPoint' as TypeEnum,
        LineString: 'LineString' as TypeEnum,
        MultiLineString: 'MultiLineString' as TypeEnum,
        Polygon: 'Polygon' as TypeEnum,
        MultiPolygon: 'MultiPolygon' as TypeEnum,
        GeometryCollection: 'GeometryCollection' as TypeEnum
    };
}


