/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Geometry } from './geometry';
import { GeometryElementAllOf } from './geometryElementAllOf';


/**
 * Abstract type for all GeoJSon \'Geometry\' object the type of which is not \'GeometryCollection\'
 */
export interface GeometryElement extends GeometryElementAllOf {
}
export namespace GeometryElement {
}


