/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoJsonSliceResponse } from './geoJsonSliceResponse';
import { GeoJsonSliceResponseCollection } from './geoJsonSliceResponseCollection';
import { GeoJsonSliceResponseMetadata } from './geoJsonSliceResponseMetadata';


/**
 * @type InlineResponse2001
 * @export
 */
export type InlineResponse2001 = Array<number> | GeoJsonSliceResponse;

