/**
 * CbrnAlert API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPoint } from './geoPoint';
import { WindVelocity } from './windVelocity';


export interface WindAtp45Input { 
    /**
     * Array of release points
     */
    locations: Array<GeoPoint>;
    procedureTypeId: string;
    containerId: string;
    incidentTypeId: string;
    wind: WindVelocity;
    stabilityClass: WindAtp45Input.StabilityClassEnum;
}
export namespace WindAtp45Input {
    export type StabilityClassEnum = 'Unstable' | 'Neutral' | 'Stable';
    export const StabilityClassEnum = {
        Unstable: 'Unstable' as StabilityClassEnum,
        Neutral: 'Neutral' as StabilityClassEnum,
        Stable: 'Stable' as StabilityClassEnum
    };
}


